### ISSUE TITLE
Every time it goes to the title screen it crashes immediately 

### ISSUE THREAD

**Issue by blazingcody0707** [Pseurae/snakewood-improved#1]
Can you please somehow fix this please

**Comment by Pseurae** [comment]
Are you building it from source or using the release patch?
The latest release patch requires a Ruby 1.0 rom, while the source code needs a pre-patched Snakewood rom.

**Comment by blazingcody0707** [comment]
From source it does a red screen with a glitch pokemon logo on the title screen

**Comment by blazingcody0707** [comment]
Here what it does on pizza boy and it did the samething on mgba on my windows laptop
![Screenshot_20241007_000829_Pizza Boy A Pro](https://github.com/user-attachments/assets/479364b9-dac1-4526-94c8-fede8e6cda45)

**Comment by blazingcody0707** [comment]
I done it under wsl noble numbat

**Comment by blazingcody0707** [comment]
Here's what it does under mgba 
![Screenshot 2024-10-07 003136](https://github.com/user-attachments/assets/f3cfa692-9925-47e5-95d1-4447c9777b30)

**Comment by Pseurae** [comment]
You sure you're using a Snakewood rom patched on Ruby 1.0?

**Comment by blazingcody0707** [comment]
i patched one on  USA, Europe Rev 2 rom and downloaded a snakewood rom from pokeharbor still same issue

**Comment by Pseurae** [comment]
Patching it on a Rev 2 rom wouldn't work, but I don't know why using the prepatched one doesn't work.

**Comment by blazingcody0707** [comment]
it could be the new logo because when you didn't add the new logo it worked but when you did add it stopped working try building it yourself to see what the issue Is for you tho

**Comment by Pseurae** [comment]
There is no issue on my end, that's why I seem so confused. It works properly on my end.

**Comment by blazingcody0707** [comment]
i had to freshly build armips again but under termux proot-distro ubuntu to get it to work i dont know why it stopped working after i just built it under wsl noble

**Comment by Pseurae** [comment]
That's weird, considering I build it through WSL now. If it works for you now, can I close the issue?

**Comment by blazingcody0707** [comment]
yes you can now thank you
