### ISSUE TITLE
suggestion can you somehow add autocase to the hack and is it possible to add gen 1-9 if you want to add gen 1-9 to the hack tho and some mons from the gigaleak if that is even possible

### ISSUE THREAD

**Issue by blazingcody0707** [Pseurae/snakewood-improved#2]

**Comment by Pseurae** [comment]
What is autocase?

**Comment by blazingcody0707** [comment]
once you hit a upercase letter  it automaticaly goes to lowercase leters in the naming your character and nicknaming the pokemon

**Comment by blazingcody0707** [comment]
here,s some more information about it Naming now auto switch to lowercase if the first letter is uppercase.

**Comment by Pseurae** [comment]
Check out 863e6149383f2f806e7f188ce5deb80c1c21216f
